#! /bin/bash

set -e

debug() {
    local -r fmt=$1
    local -a arg=("${@:2}")
    local -r str=$(printf "$fmt" $arg)

    printf '[debug] %s\n' "$str"
}

subject='screensaver launch'
# XXX mate-settings-daemon, on which we rely on for hidpi settings, starts
#     mate-screensaver and interferes with our start.
debug 'Starting killing loop'
# FIXME What if mate-screensaver is not running AND is not going to run? This will loop forever in vain!
while ! pkill mate-screensave
do
    debug 'Failed to kill'
    notify-send -u low "$subject" 'Failed to kill mate-screensaver'
    sleep 1
done
debug 'Killed. Starting new.'
notify-send -u low "$subject" 'Killed mate-screensaver. Starting xscreensaver'

xscreensaver
